### ISSUE TITLE
Swipe to refresh doesn't handle rotation very well.

### ISSUE THREAD

**Issue by Tom-Johnston** [Tom-Johnston/LMH#72]

**Comment by unpairedbracket** [comment]
The layout itself seems to have issues with starting the animation too early in the application lifecycle. It doesn't seem to work in onCreate, or the initial fragment's onCreateView. Not sure why this is, or how to fix it.

**Comment by unpairedbracket** [comment]
Fixed as per [niks.stack's answer](http://stackoverflow.com/questions/26858692/swiperefreshlayout-setrefreshing-not-showing-indicator-initially)
