### ISSUE TITLE
onRefresh is firing far too often in the Menu fragment.

### ISSUE THREAD

**Issue by Tom-Johnston** [Tom-Johnston/LMH#73]
It seems to be happen on any click event and when opening the drawer.

**Comment by unpairedbracket** [comment]
Unable to replicate. Refresh animation doesn't show when the recycler's not around for some reason, but it's not trying to refresh on touch

**Comment by unpairedbracket** [comment]
Seems to be solved by making the recycler always visible. Don't know why.
