### ISSUE TITLE
The app seems to have spontaneously stopped working.

### ISSUE THREAD

**Issue by Tom-Johnston** [Tom-Johnston/LMH#74]

**Comment by Tom-Johnston** [comment]
Trying to access the intranet when not logged in appears to be hanging even on Chrome.

**Comment by Tom-Johnston** [comment]
It might just be being really slow.

**Comment by unpairedbracket** [comment]
It's working for me at the moment

**Comment by Tom-Johnston** [comment]
I think it was just a problem with webauth being really slow.
